### ISSUE TITLE
readme update suggestion 

### ISSUE THREAD

**Issue by kailakx** [flossway/flossway#39]
With more discussion we had and more contributors join in, it maybe the time to have an update on this readme file in order to describe more precisely the vision and purpose of this project. And then we all will share a clear mutual understanding on that, meanwhile, to attract more content contributors to work together and collaborate actively.

Suggestions of Why, What, Who, and How shall be in this project is welcomed. @tisonkun @zhuangbiaowei @gujun720

**Comment by tisonkun** [comment]
I'm looking into this issue now. Please don't assign others but using `@somebody` instead (it should be enough).

**Comment by tisonkun** [comment]
@kailakx your suggestion is general good, but could you elaborate what you propose to be added into the README file? Otherwise this issue is too vague to proceed.

**Comment by tisonkun** [comment]
Closed as no progress. Feel free to reopen it with more information.
